import { SEO_DESCRIPTION_MAX, SEO_TITLE_MAX } from '@calwebtech/shared';
import type { Metadata } from 'next';
import { SITE_NAME, absoluteUrl, sitePath } from './site';

/** Generated by app/opengraph-image.tsx; used when a page has no image of its own. */
export const DEFAULT_OG_IMAGE = {
  // With the trailing slash every site URL has, so crawlers are not redirected.
  path: '/opengraph-image/',
  width: 1200,
  height: 630,
  alt: 'Calwebtech: custom websites, commerce platforms and web applications',
} as const;

const collapse = (value: string) => value.replace(/\s+/g, ' ').trim();

/**
 * Shortens copy to `max` characters at a word boundary. With `ellipsis`, the result ends
 * with "…" inside the limit.
 */
export function clampText(value: string, max: number, ellipsis = true): string {
  const text = collapse(value);
  if (text.length <= max) return text;
  const room = ellipsis ? max - 1 : max;
  const window = text.slice(0, room + 1);
  const boundary = window.lastIndexOf(' ');
  const cut = boundary >= Math.floor(room * 0.6) ? window.slice(0, boundary) : text.slice(0, room);
  const clean = cut.replace(/[\s,;:.–-]+$/u, '');
  return ellipsis ? `${clean}…` : clean;
}

/**
 * The document title: the page's own title with " | Calwebtech" when that fits in 60
 * characters (docs/04-seo-keyword-map.md), otherwise the title alone, shortened if needed.
 */
export function seoTitle(title: string): string {
  const clean = collapse(title);
  const branded = `${clean} | ${SITE_NAME}`;
  if (!clean.includes(SITE_NAME) && branded.length <= SEO_TITLE_MAX) return branded;
  return clampText(clean, SEO_TITLE_MAX, false);
}

/** The meta description, at most 155 characters. */
export function seoDescription(description: string): string {
  return clampText(description, SEO_DESCRIPTION_MAX);
}

export interface PageMetadataInput {
  /** The page's own title, without the brand. */
  title: string;
  description: string;
  /** The page's path, e.g. `/services/website-redesign/`. */
  path: string;
  /** False renders noindex, nofollow. */
  indexable: boolean;
  /**
   * Where the canonical points when it is not the page itself: a filtered listing that is
   * not a deliberate target canonicalises to its unfiltered parent.
   */
  canonicalPath?: string;
  /** A site path or URL; the generated default image when absent. */
  ogImage?: string | null;
  ogImageAlt?: string;
  type?: 'website' | 'article';
}

/**
 * Metadata for a site page: the title and description length rules, an absolute canonical
 * on APP_ORIGIN, Open Graph and Twitter cards, and robots. Every site page builds its
 * metadata here, through `sitePageMetadata` (page-metadata.ts), which supplies `indexable`.
 */
export function buildMetadata(input: PageMetadataInput): Metadata {
  const title = seoTitle(input.title);
  const description = seoDescription(input.description);
  const canonical = absoluteUrl(sitePath(input.canonicalPath ?? input.path));
  const image = input.ogImage
    ? { url: absoluteUrl(input.ogImage), alt: input.ogImageAlt ?? title }
    : {
        url: absoluteUrl(DEFAULT_OG_IMAGE.path),
        width: DEFAULT_OG_IMAGE.width,
        height: DEFAULT_OG_IMAGE.height,
        alt: DEFAULT_OG_IMAGE.alt,
      };

  return {
    title: { absolute: title },
    description,
    alternates: { canonical },
    robots: input.indexable ? { index: true, follow: true } : { index: false, follow: false },
    openGraph: {
      type: input.type ?? 'website',
      siteName: SITE_NAME,
      locale: 'en_US',
      title,
      description,
      url: canonical,
      images: [image],
    },
    twitter: { card: 'summary_large_image', title, description, images: [image.url] },
  };
}
